name: Boost
version: 1.17.1
author: pmme
api-version: 1.13
main: nz.pmme.Boost.Main

load: POSTWORLD
softdepend:
  - Multiverse-Core
  - PlaceholderAPI

commands:
  boost:
    description: 'Enter "/boost" with no options for help.'
    usage: /<command>
    aliases: bst
    permission: boost.cmd
    permission-message: 'You do not have permission to use that command.'

permissions:
  boost.join:
    description: 'Permission to join a Boost game'
    default: true
  boost.cmd:
    description: 'Permission to use Boost player commands'
    default: true
  boost.admin:
    description: 'Permission to use Boost admin commands'
    default: op
  boost.status:
    description: 'Permission to fetch Boost game status'
    default: true
  boost.bypassblocking:
    description: 'Permission to bypass command blocking while playing'
    default: op
  boost.*:
    description: 'Grant all Boost permissions'
    default: op
    children:
      boost.join: true
      boost.cmd: true
      boost.admin: true
      boost.status: true
      boost.bypassblocking: true
